[tool.poetry]
name = "gomoku-python"
version = "0.1.0"
description = "A gomoku game writtne in python"
authors = ["Jerry <jerrycgh@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
